### ISSUE TITLE
Unknown node type TSAsExpression for no-nested-subscribe

### ISSUE THREAD

**Issue by Gyomu** [cartant/eslint-plugin-rxjs#38] opened 2019-10-24 09:37 UTC
Hello,

Using `eslint@6.5.1` and `eslint-plugin-rxjs@0.0.1-beta.4`

I recently added the rxjs/no-nested-subscribe rule with default config, and it makes ESlint crash with the following error:
`Error: Unknown node type TSAsExpression.`

The config I'm using is :
```jsonc
"parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
        "project": "./tsconfig.json"
    },
// ...
"rules": {
    // ...
    "rxjs/no-nested-subscribe": "error",
    // ...
}
```

If I remove this one rule, everything is working fine.

On the source code part, indeed there is a nested subscribe, which is when it's failing.

I have yet to get a clue about why and how it is breaking.

**Comment by cartant** [comment] 2019-10-24 09:44
Do you have the latest version of `@typescript-eslint/parser`?

**Comment by Gyomu** [comment] 2019-10-24 09:44
2.5.0 yes

**Comment by cartant** [comment] 2019-10-24 09:49
Run `yarn outdated` - or whatever the `npm` equivalent is - to make sure that you have the latest versions of all the ESLint and TypeScript packages.

**Comment by Gyomu** [comment] 2019-10-24 09:55
I'll check the dependencies of the packages.. so far no outdated packages related to eslint or typescript-eslint reported.

**Comment by Gyomu** [comment] 2019-10-25 10:09
I managed to reproduce the behavior on a small portion of code. Take this for example:
```typescript
import {of} from "rxjs";

 of(3).subscribe(result => {
    const test = result as boolean;
    if(test > 1) {
      console.log(test);
    }
  });
```

This will produce the above mentioned error:
```text
Error: Unknown node type TSAsExpression.
Occurred while linting /dev/rca-eslint/rca/src/app/app.component.ts:30
    at Controller.traverse (/dev/rca-eslint/rca/node_modules/estraverse/estraverse.js:454:31)
    at Object.traverse (/dev/rca-eslint/rca/node_modules/estraverse/estraverse.js:646:27)
    at match (/dev/rca-eslint/rca/node_modules/esquery/esquery.js:288:24)
    at Object.query [as default] (/dev/rca-eslint/rca/node_modules/esquery/esquery.js:322:20)
    at /dev/rca-eslint/rca/node_modules/eslint-plugin-rxjs/dist/rules/no-nested-subscribe.js:28:57
    at Array.forEach (<anonymous>)
    at CallExpression > MemberExpression[property.name='subscribe'] (/dev/rca-eslint/rca/node_modules/eslint-plugin-rxjs/dist/rules/no-nested-subscribe.js:27:42)
    at /dev/rca-eslint/rca/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/dev/rca-eslint/rca/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

The part that triggers the error is the cast you see here:
```typescript
result as boolean
```
while the `result` variable was implicitly typed as `any`

It seems to me that the error message is misleading, and is not due to the AST type `TSAsExpression` being unknown. But something else entirely. But sadly I'm no expert of the Typescript AST and the current traverser to pinpoint the exact issue. I'll keep looking into this just in case.

**Comment by cartant** [comment] 2019-10-25 10:15
I can't check it, ATM, but you could try parsing that code using:

https://astexplorer.net/

Make sure you use the TypeScript ESLint parser. TBH, this.does not sound like a bug in this package. It will be interesting to see what happens.

**Comment by cartant** [comment] 2019-10-25 10:47
Hmm, seems fine in AST explorer. Interesting.

https://astexplorer.net/#/gist/eb7820c848396a9025d0f67cb6438c74/5efea98132bcf65b50b7a1750046bb569bbc5c3f

**Comment by cartant** [comment] 2019-10-25 20:51
There is no quick fix for this. The problem is the use of `esquery` in the rule implementation: if `estraverse` - which it uses internally - sees an unexpected node type, it explodes. The simplest solution is likely to be forking `esquery` and using an alternative traversal implementation.

`esquery` is used in the implementations of three other rules in this package, too.

**Comment by cartant** [comment] 2019-10-26 00:35
This should be fixed in `0.0.1-beta.5`. The fix wasn't actually that difficult, as `estraverse` is configurable and the TypeScript parser for ESLint exposes what's needed for the configuration.

**Closed** 2019-10-26 00:40 UTC
Labels: bug

**Comment by Gyomu** [comment] 2019-10-28 05:54
Thank you for the fix and the help to diagnose this !

**Comment by cartant** [comment] 2019-10-28 05:56
No worries. Thanks for reporting it.

**Comment by dpraul** [comment] 2020-03-02 16:27
@cartant  I'm experiencing this same issue on `0.0.2-beta.16`. The example code provided in https://github.com/cartant/eslint-plugin-rxjs/issues/38#issuecomment-546292889 triggers the issue just the same as it did before.

**Comment by cartant** [comment] 2020-03-02 22:31
@dpraul This repo includes a test - taken from this issue - passes with the latest versions installed:

https://github.com/cartant/eslint-plugin-rxjs/blob/a6f4e5ec25a70f1a68b3bf7acf4ba7a477feacba/tests/rules/no-nested-subscribe.ts#L43-L52

You would have to provide a minimal reproduction for this to be taken further.

Also, IMO, maintainers prefer to have new issues opened rather than to have people comment on closed issues. In future, I would recommend your not commenting on closed issues and, instead, opening a new issue from within which you can reference the issue upon which would would otherwise have commented.
